name: Build
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: Run Build 
      run: pnpm run build
  Lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: Run lint 
      run: pnpm run lint       