name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  UnitTest:
    runs-on: unbuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: Run Test 
      run: pnpm run test
  Lint:
    runs-on: unbuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: Run Lint 
      run: pnpm run lint
  Build:
    runs-on: unbuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: build 
      run: pnpm run build   